#pragma once

#define WINDOW_WIDTH 1600
#define WINDOW_HEIGHT 900

#define FPS 60.0f

#define CAMERA_MODE 1
#define BASE_RANGE 600.0f
#define BASE_CAMERA_X 450
#define BASE_CAMERA_Y 0
#define BASE_CAMERA_Z 350
#define CAMERA_DISTANCE_STEP 5
#define MIN_CAMERA_DISTANCE_SCALE -20
#define MAX_CAMERA_DISTANCE_SCALE 25